### ISSUE TITLE
Example folder of the repo.

### ISSUE THREAD

**Issue by hmok** [pyomeca/tutorials#2]
Hello,

I am wondering if you have moved your examples folder [here](https://github.com/pyomeca/pyosim/tree/master/examples)

I was trying to do some of your tutorials. Also, when you read marker and force data from c3d files, I wonder if they are in OpenSim coordinate system. I could not find any rotation in the codes. Or I am missing it. I was looking for something like [this ](https://github.com/opensim-org/opensim-core/blob/master/Bindings/Java/Matlab/Utilities/osimC3D.m)that has been written in Matlab. 

I am looking to your new tutorials and applying them.

Cheers,
Hossein

**Comment by romainmartinez** [comment]
Hi there,

If you talk about pyosim, I moved the examples folder [here](https://github.com/romainmartinez/pyosim_aws/tree/master/pipeline) as they were not really tutorial/examples but rather complete analysis scripts that we use.

If the marker or force data in the c3d does not match your model, you can apply a rotation transformation on the data. As our classes inherit from numpy array, you can do this transformation as if it was a standard numpy nd-array.

Or you can directly change the coordinates system in your `osim` model.

**Comment by hmok** [comment]
Thanks guys! I will try what you suggested.

**Comment by hmok** [comment]
Hello guys,

I am trying to get the evens and their frame number in a C3D file. e.g. in BTK it was like this:

_for event in btk.Iterate(acq.GetEvents()):
      if event.GetFrame() >= n:_
....

I can get events using ezc3d this way:
c3d['parameters']['EVENT_CONTEXT']['USED']['value']

I am not sure if I am missing it, but I cannot get event frames.

Thank you.
Cheers,
Hossein

**Comment by pariterre** [comment]
Hi @hmok 
I have never used events so far. According to the standard, the EVENT_CONTEXT group and EVENT group work together, the latter including the parameter "TIMES". My first guess would be to look over there. 
Please note that since these goups are not mandatory groups, they are less standardize (meaning that it depends on the software that produced the C3D and sometime the version). 

My second guess would be to look in the header (instead of parameters), since Event time is mandatory. So I assume that the C3D fill it. 

If it doesn't help, please send me the C3D, I can further investigate!

Have a nice day

**Comment by hmok** [comment]
Hi @romainmartinez 

Thanks for the response. I think I know what the problem is. I guess you created 18 events as None in the original code and when I read them, it cannot identify the new events and it overrides them by the default values.

You are right, I think the time and evens are in the header. I will email you a C3D file (to pariterre@hotmail.com). And I would be happy to have your insight on how to read the events and their timings.

Cheers,
Hossein

**Comment by pariterre** [comment]
Hi @hmok,
So I've had a look a the C3D you gave me. Unlike I expected, the values are not in the header, they actually have left the header empty for the event parameter. Therefore, the values are in the parameter section. 

As suggested before, in your file I could find time stamps in c['parameters']['EVENT']['TIMES']['value'] (rather than in EVENT_CONTEXT). However I am not sure they are the values you are looking for... 

Does that help?

**Comment by hmok** [comment]
Hi @pariterre ,

It is great. Thank you! they are the right time stamps. It includes all the time stamps; however, I am not sure why it has 0s before each time stamp. 
(0.0, 2.9600000381469727, 0.0, 3.9700000286102295, 0.0, 3.240000009536743)

But this is the information I need. Thanks again!
Cheers,
Hossein

**Comment by pariterre** [comment]
Sweet, 
Yep, I am not sure why they put zeros over there either... 

Glad it helped!

See you :)
